### ISSUE TITLE
Implement a Logo in the middle of QR code

### ISSUE THREAD

**Issue by johnalbert-dot-py** [dprog-philippe-docourt/django-qr-code#22]
Can we implement a  Logo inside of a QR code right in the middle of it?

**Comment by philippe-docourt** [comment]
This is not available out-of-the-box.

However you can overlay an image on top of the QR code image by using CSS rules. In order to keep the code readable, you'll need to increase the error correction level. That way the QR code contains more redundant data and it can be read even though your image hides one part of it.
