### ISSUE TITLE
Possible to not use templates?

### ISSUE THREAD

**Issue by pljspahn** [dprog-philippe-docourt/django-qr-code#28]
I'd like to use a class-based `DetailView` that overrides `render_to_response` to serve a qr code image via `FileResponse` directly instead of using a template. 

For example, my url pattern `localhost/MY-SAVED-OBJECT` will return the image saved to an `ImageField` on the model via `FileResponse`. I want an additional url pattern such as `localhost/qr/MY-SAVED-OBJECT` to do the same thing but with the generated qr code. 

Can I use this module for doing that or should I look at the Segno library instead?

**Comment by philippe-docourt** [comment]
In case you want to mix preview of QR codes in your pages with QR codes saved as images, using this module might be a good idea, since you'll have one uniform API to do both things (see maker.make_qr_code_image for generating the image file).

However, if you are sure that you only want to create images, Segno is probably a simpler way.

NB: Both libraries provides helpers to build specific QR codes like Wi-Fi connexion, contact cards, etc.
