### ISSUE TITLE
How can  generate QR code as a png image for a link?

### ISSUE THREAD

**Issue by IProudNoob** [dprog-philippe-docourt/django-qr-code#34]
I need generate QR in format:
site.com/info/016511c1-a53f-4a21-b5f4-6864a074a64c/qrcode.png
or
site.com/info/016511c1-a53f-4a21-b5f4-6864a074a64c.png

It can be done?
If so, how?

THX 👍 )

**Comment by philippe-docourt** [comment]
@IProudNoob, in order to achieve what I'm guessing you want, you can write your own view attached to your desired URL scheme and then call `qr_code.views.serve_qr_code_image` to handle the image generation. Please check out the documentation of `serve_qr_code_image` function to see the available options - passed as query string arguments - to adjust the appearance of the returned QR code.
